<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserBalanceController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserSearchController;

/** 
 * Here’s a complete structure with  
 * detailed comments and paths for the    
 * URL, resource views, controller 
 * structure, and URL parameters:
 * Application Routes and Structure
 * URL: https://EliteTools.life/m/
 * 
 * Route Groups:
 * 1. Welcome Page (Public)
 * 2. Authentication (Public and Protected)
 * 3. Admin Panel (Protected, Requires Admin Privileges)
 */

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
|
| Public page that loads the welcome view.
| Accessible by everyone.
|
*/
Route::get('/', fn() => view('welcome'))->name('welcome'); // URL: https://EliteTools.life/m/

/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| Grouped routes for user authentication - Registration, Login, Password Reset.
| Protected routes are restricted to authenticated users.
|
*/

// Default Laravel Auth routes for login, registration, password reset, etc.
Auth::routes(); // Auto-generated by Laravel: Includes routes like /login, /register, etc.

// Public Routes for Guests
Route::middleware(['guest', 'check.session.login'])->group(function () {
    /**
     * Show Registration Form
     * URL: https://EliteTools.life/m/register
     * View: resources/views/user/register.blade.php
     */
    Route::get('/register', fn() => view('user.register'))->name('register.form');
    
    /**
     * Handle User Registration
     * URL: https://EliteTools.life/m/register
     * Controller: AuthController@register
     * Path: app/Http/Controllers/AuthController.php
     */
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    /**
     * Show Login Form
     * URL: https://EliteTools.life/m/login
     * View: resources/views/user/login.blade.php
     */
    Route::get('/login', fn() => view('user.login'))->name('login.form');
    
    /**
     * Handle User Login
     * URL: https://EliteTools.life/m/login
     * Controller: AuthController@login
     * Path: app/Http/Controllers/AuthController.php
     */
    Route::post('/login', [AuthController::class, 'login'])->name('login');
});

// Protected Routes for Authenticated Users
Route::middleware(['auth', 'check.session.login'])->group(function () {
    /**
     * User's Dashboard
     * URL: https://EliteTools.life/m/home
     * View: resources/views/home.blade.php
     */
    Route::get('/home', fn() => view('home'))->name('home');

    /**
     * Handle User Logout
     * URL: https://EliteTools.life/m/logout
     * Controller: AuthController@logout
     * Path: app/Http/Controllers/AuthController.php
     */
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    /**
     * Verify User Email
     * URL: https://EliteTools.life/m/email-verify/{userId}
     * Controller: AuthController@verifyEmail
     * Path: app/Http/Controllers/AuthController.php
     */
    Route::post('/email-verify/{userId}', [AuthController::class, 'verifyEmail'])->name('email.verify');

    /**
     * Reset User Password
     * URL: https://EliteTools.life/m/password-reset
     * Controller: AuthController@resetPassword
     * Path: app/Http/Controllers/AuthController.php
     */
    Route::post('/password-reset', [AuthController::class, 'resetPassword'])->name('password.reset');
});

/*
|--------------------------------------------------------------------------
| Admin Routes (Only for Users with Admin Privileges)
|--------------------------------------------------------------------------
|
| Admin routes are prefixed with 'admin' and restricted to users with 'can:access-admin'
| middleware. All admin views are located in resources/views/admin.
|
*/

Route::middleware(['auth', 'can:access-admin'])->prefix('admin')->name('admin.')->group(function () {

    /*
    |--------------------------------------------------------------------------
    | Admin Dashboard
    |--------------------------------------------------------------------------
    |
    | Admin dashboard route. Accessible to admins only.
    |
    */
    Route::controller(DashboardController::class)->group(function () {
        /**
         * Admin Dashboard Home
         * URL: https://EliteTools.life/m/admin
         * View: resources/views/admin/dashboard.blade.php
         */
        Route::get('/', 'index')->name('dashboard');
    });

    /*
    |--------------------------------------------------------------------------
    | User Management Routes
    |--------------------------------------------------------------------------
    |
    | Routes for managing users: list, search, edit, update, delete.
    | All views for user management are in resources/views/admin/users/.
    |
    */
Route::prefix('users')->name('users.')->controller(UserController::class)->group(function () {





/**
         * List All Users
         * URL: https://EliteTools.life/m/admin/users
         * View: resources/views/admin/users/index.blade.php
         */
    Route::get('/all', 'allUsers')->name('all');
});
        /**
         * List All Usersp
         * URL: https://EliteTools.life/m/admin/users
         * View: resources/views/admin/users/index.blade.php
         */
        Route::get('/', 'index')->name('index');
        
        /**
         * Search Users
         * URL: https://EliteTools.life/m/admin/users/search
         * View: resources/views/admin/users/search.blade.php
         */
        Route::get('/search', 'search')->name('search');
        
        /**
         * Edit User
         * URL: https://EliteTools.life/m/admin/users/{user_id}/edit
         * View: resources/views/admin/users/edit.blade.php
         */
        Route::get('/{user_id}/edit', 'edit')->name('edit');
        
        /**
         * Update User
         * URL: https://EliteTools.life/m/admin/users/{user_id}/update
         * Controller: UserController@update
         * Path: app/Http/Controllers/Admin/UserController.php
         */
        Route::post('/{user_id}/update', 'update')->name('update');
        
        /**
         * Delete User
         * URL: https://EliteTools.life/m/admin/users/{user_id}/delete
         * Controller: UserController@delete
         * Path: app/Http/Controllers/Admin/UserController.php
         */
        Route::post('/{user_id}/delete', 'delete')->name('delete');
        
        /**
         * Activate User as Seller
         * URL: https://EliteTools.life/m/admin/users/{user_id}/activate-seller
         * Controller: UserController@activate
         * Path: app/Http/Controllers/Admin/UserController.php
         */
        Route::post('/{user_id}/activate', 'activate')->name('activate');

        /*
        |--------------------------------------------------------------------------
        | Manage Users with Balance
        |--------------------------------------------------------------------------
        |
        | Manage users with a balance, only accessible from the user management section.
        |
        */
        Route::prefix('with-balance')->name('with-balance.')->group(function () {
            /**
             * List Users with Balance
             * URL: https://EliteTools.life/m/admin/users/with-balance
             * View: resources/views/admin/users/with-balance.blade.php
             */
            Route::get('/', 'index')->name('index');
        });
    });

    /*
    |--------------------------------------------------------------------------
    | User Balance Management
    |--------------------------------------------------------------------------
    |
    | Routes for managing user balances: view, search, and update.
    |
    */
    Route::prefix('users/balance')->name('users.balance.')->controller(UserBalanceController::class)->group(function () {
        /**
         * View User Balances
         * URL: https://EliteTools.life/m/admin/users/balance
         * View: resources/views/admin/users/balance/index.blade.php
         */
        Route::get('/', 'index')->name('index');
        
        /**
         * Search User Balances
         * URL: https://EliteTools.life/m/admin/users/balance/search
         * View: resources/views/admin/users/balance/search.blade.php
         */
        Route::get('/search', 'search')->name('search');
        
        /**
         * Edit User Balance
         * URL: https://EliteTools.life/m/admin/users/balance/{user_id}/edit
         * View: resources/views/admin/users/balance/edit.blade.php
         */
        Route::get('/{user_id}/edit', 'edit')->name('edit');
        
        /**
         * Update User Balance
         * URL: https://EliteTools.life/m/admin/users/balance/{user_id}/update
         * Controller: UserBalanceController@update
         * Path: app/Http/Controllers/Admin/UserBalanceController.php
         */
        Route::post('/{user_id}/update', 'update')->name('update');

})


    })
/***


Explanation:

	1.	URL Structure: This structure uses meaningful paths, with public routes (e.g., /register, /login) and protected routes (e.g., /admin, /admin/users).
	2.	Resource Views:
	•	Views for authentication are located in resources/views/user/.
	•	Admin views are located in resources/views/admin/.
	3.	URL Parameters: For dynamic paths like user IDs, parameters are used in routes, such as {user_id} in /admin/users/{user_id}/edit.
	4.	Controller Structure: Controllers are placed in app/Http/Controllers/:
	•	AuthController handles user registration and login.
	•	DashboardController handles the admin dashboard.
	•	UserController handles user management.
	•	UserBalanceController handles user balance management.

Each route is clearly defined to ensure a well-structured application, making it easy to scale and maintain.
***/
